// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantManagement.Models.Entities;

#nullable disable

namespace RestaurantManagement.Migrations
{
    [DbContext(typeof(QLNhaHangContext))]
    [Migration("20251105171225_ThemCotGioiTinh")]
    partial class ThemCotGioiTinh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CungCap", b =>
                {
                    b.Property<int>("IdnhaCungCap")
                        .HasColumnType("int")
                        .HasColumnName("IDNhaCungCap");

                    b.Property<int>("IdnguyenLieu")
                        .HasColumnType("int")
                        .HasColumnName("IDNguyenLieu");

                    b.HasKey("IdnhaCungCap", "IdnguyenLieu")
                        .HasName("PK__CungCap__A5BD74429467ED85");

                    b.HasIndex("IdnguyenLieu");

                    b.ToTable("CungCap", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.BanAn", b =>
                {
                    b.Property<int>("IdbanAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDBanAn");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdbanAn"));

                    b.Property<string>("LoaiBan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SucChua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdbanAn")
                        .HasName("PK__BanAn__39899B20481D5716");

                    b.ToTable("BanAn", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.ChiTietHoaDon", b =>
                {
                    b.Property<int>("IdhoaDon")
                        .HasColumnType("int")
                        .HasColumnName("IDHoaDon");

                    b.Property<int>("IdmonAn")
                        .HasColumnType("int")
                        .HasColumnName("IDMonAn");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdhoaDon", "IdmonAn")
                        .HasName("PK__ChiTietH__7208CE0FEB303B17");

                    b.HasIndex("IdmonAn");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("IdphieuNhapKho")
                        .HasColumnType("int")
                        .HasColumnName("IDPhieuNhapKho");

                    b.Property<int>("IdnguyenLieu")
                        .HasColumnType("int")
                        .HasColumnName("IDNguyenLieu");

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.HasKey("IdphieuNhapKho", "IdnguyenLieu")
                        .HasName("PK__ChiTietP__7EDD060DA488CBFA");

                    b.HasIndex("IdnguyenLieu");

                    b.ToTable("ChiTietPhieuNhap", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.DatBan", b =>
                {
                    b.Property<int>("IddatBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDatBan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IddatBan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IdbanAn")
                        .HasColumnType("int")
                        .HasColumnName("IDBanAn");

                    b.Property<int?>("IdkhachHang")
                        .HasColumnType("int")
                        .HasColumnName("IDKhachHang");

                    b.Property<int?>("SoLuongKh")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongKH");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IddatBan")
                        .HasName("PK__DatBan__9CFC96CA0B7FC3DA");

                    b.HasIndex("IdbanAn");

                    b.HasIndex("IdkhachHang");

                    b.ToTable("DatBan", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.HoaDon", b =>
                {
                    b.Property<int>("IdhoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDHoaDon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdhoaDon"));

                    b.Property<int>("BanAnIdbanAn")
                        .HasColumnType("int");

                    b.Property<int>("DatBanIddatBan")
                        .HasColumnType("int");

                    b.Property<int?>("IdbanAn")
                        .HasColumnType("int")
                        .HasColumnName("IDBanAn");

                    b.Property<int?>("IddatBan")
                        .HasColumnType("int")
                        .HasColumnName("IDDatBan");

                    b.Property<int?>("IdkhachHang")
                        .HasColumnType("int")
                        .HasColumnName("IDKhachHang");

                    b.Property<int?>("IdnhanVien")
                        .HasColumnType("int")
                        .HasColumnName("IDNhanVien");

                    b.Property<int>("KhachHangIdkhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ThoiGianGiao")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdhoaDon")
                        .HasName("PK__HoaDon__5B896F49A6180061");

                    b.HasIndex("BanAnIdbanAn");

                    b.HasIndex("DatBanIddatBan");

                    b.HasIndex("IdbanAn");

                    b.HasIndex("IddatBan");

                    b.HasIndex("IdkhachHang");

                    b.HasIndex("IdnhanVien");

                    b.HasIndex("KhachHangIdkhachHang");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.KhachHang", b =>
                {
                    b.Property<int>("IdkhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDKhachHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdkhachHang"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTenKh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoTenKH");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.HasKey("IdkhachHang")
                        .HasName("PK__KhachHan__5A7167B54581CC1A");

                    b.HasIndex(new[] { "Email" }, "UQ__KhachHan__A9D10534B2B15251")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex(new[] { "Sdt" }, "UQ__KhachHan__CA1930A5AD35A601")
                        .IsUnique()
                        .HasFilter("[SDT] IS NOT NULL");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.Kho", b =>
                {
                    b.Property<int>("Idkho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDKho");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idkho"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Idkho")
                        .HasName("PK__Kho__939E101782446E63");

                    b.ToTable("Kho", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.MonAn", b =>
                {
                    b.Property<int>("IdmonAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDMonAn");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdmonAn"));

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdmonAn")
                        .HasName("PK__MonAn__981A14636D5F2EB0");

                    b.HasIndex(new[] { "TenMon" }, "UQ__MonAn__332EF56534AB0ACB")
                        .IsUnique();

                    b.ToTable("MonAn", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.MonAnNguyenLieu", b =>
                {
                    b.Property<int>("IdmonAn")
                        .HasColumnType("int")
                        .HasColumnName("IDMonAn");

                    b.Property<int>("IdnguyenLieu")
                        .HasColumnType("int")
                        .HasColumnName("IDNguyenLieu");

                    b.Property<double>("SoLuongCan")
                        .HasColumnType("float");

                    b.HasKey("IdmonAn", "IdnguyenLieu")
                        .HasName("PK__MonAn_Ng__7A13E4EC21BB9103");

                    b.HasIndex("IdnguyenLieu");

                    b.ToTable("MonAn_NguyenLieu", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.NguyenLieu", b =>
                {
                    b.Property<int>("IdnguyenLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNguyenLieu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdnguyenLieu"));

                    b.Property<string>("DonVi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Loai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNL");

                    b.HasKey("IdnguyenLieu")
                        .HasName("PK__NguyenLi__209F08FFB06641A3");

                    b.HasIndex(new[] { "TenNl" }, "UQ__NguyenLi__4CF9B492CE50D4D5")
                        .IsUnique();

                    b.ToTable("NguyenLieu", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.NhaCungCap", b =>
                {
                    b.Property<int>("IdnhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNhaCungCap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdnhaCungCap"));

                    b.Property<string>("DiaChiNcc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DiaChiNCC");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenNcc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenNCC");

                    b.HasKey("IdnhaCungCap")
                        .HasName("PK__NhaCungC__47B484CD54A4413C");

                    b.HasIndex(new[] { "Sdt" }, "UQ__NhaCungC__CA1930A516E7692B")
                        .IsUnique()
                        .HasFilter("[SDT] IS NOT NULL");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.NhanVien", b =>
                {
                    b.Property<int>("IdnhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNhanVien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdnhanVien"));

                    b.Property<string>("Cccd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoTenNV");

                    b.Property<decimal?>("Luong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayVaoLam")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.HasKey("IdnhanVien")
                        .HasName("PK__NhanVien__7AC2D9F704E1BEDB");

                    b.HasIndex(new[] { "Email" }, "UQ__NhanVien__A9D10534A86AA149")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex(new[] { "Sdt" }, "UQ__NhanVien__CA1930A5C1CE5263")
                        .IsUnique();

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.PhieuNhapKho", b =>
                {
                    b.Property<int>("IdphieuNhapKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPhieuNhapKho");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdphieuNhapKho"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IdnhaCungCap")
                        .HasColumnType("int")
                        .HasColumnName("IDNhaCungCap");

                    b.Property<int?>("IdnhanVien")
                        .HasColumnType("int")
                        .HasColumnName("IDNhanVien");

                    b.Property<DateTime>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.HasKey("IdphieuNhapKho")
                        .HasName("PK__PhieuNha__9CD4F6821276C3F2");

                    b.HasIndex("IdnhaCungCap");

                    b.HasIndex("IdnhanVien");

                    b.ToTable("PhieuNhapKho", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.Quyen", b =>
                {
                    b.Property<int>("IDQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDQuyen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDQuyen"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDQuyen")
                        .HasName("PK__Quyen__B3A2827E970DEFBE");

                    b.HasIndex(new[] { "TenQuyen" }, "UQ__Quyen__5637EE7992E70F48")
                        .IsUnique();

                    b.ToTable("Quyen", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("IDTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTaiKhoan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTaiKhoan"));

                    b.Property<int>("IDNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("IDNhanVien");

                    b.Property<byte[]>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varbinary(255)");

                    b.Property<byte[]>("MatKhauSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varbinary(255)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Hoạt động");

                    b.HasKey("IDTaiKhoan")
                        .HasName("PK__TaiKhoan__BC5F907C1EF66573");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__TaiKhoan__55F68FC007CE6683")
                        .IsUnique();

                    b.HasIndex(new[] { "IDNhanVien" }, "UQ__TaiKhoan__7AC2D9F6D8F4C6B1")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.ThanhToan", b =>
                {
                    b.Property<int>("IdthanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDThanhToan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdthanhToan"));

                    b.Property<int>("IdhoaDon")
                        .HasColumnType("int")
                        .HasColumnName("IDHoaDon");

                    b.Property<int?>("IdkhachHang")
                        .HasColumnType("int")
                        .HasColumnName("IDKhachHang");

                    b.Property<DateTime>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhuongThuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdthanhToan")
                        .HasName("PK__ThanhToa__DC57C3A1D3E43009");

                    b.HasIndex("IdhoaDon");

                    b.HasIndex("IdkhachHang");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.TonKho", b =>
                {
                    b.Property<int>("Idkho")
                        .HasColumnType("int")
                        .HasColumnName("IDKho");

                    b.Property<int>("IdnguyenLieu")
                        .HasColumnType("int")
                        .HasColumnName("IDNguyenLieu");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.HasKey("Idkho", "IdnguyenLieu")
                        .HasName("PK__TonKho__7197E098D3AC3031");

                    b.HasIndex("IdnguyenLieu");

                    b.ToTable("TonKho", (string)null);
                });

            modelBuilder.Entity("TaiKhoanQuyen", b =>
                {
                    b.Property<int>("IdtaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("IDTaiKhoan");

                    b.Property<int>("Idquyen")
                        .HasColumnType("int")
                        .HasColumnName("IDQuyen");

                    b.HasKey("IdtaiKhoan", "Idquyen")
                        .HasName("PK__TaiKhoan__4765B85BE3A780AC");

                    b.HasIndex("Idquyen");

                    b.ToTable("TaiKhoan_Quyen", (string)null);
                });

            modelBuilder.Entity("CungCap", b =>
                {
                    b.HasOne("RestaurantManagement.Models.Entities.NguyenLieu", null)
                        .WithMany()
                        .HasForeignKey("IdnguyenLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CungCap__IDNguye__6C190EBB");

                    b.HasOne("RestaurantManagement.Models.Entities.NhaCungCap", null)
                        .WithMany()
                        .HasForeignKey("IdnhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CungCap__IDNhaCu__6B24EA82");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.ChiTietHoaDon", b =>
                {
                    b.HasOne("RestaurantManagement.Models.Entities.HoaDon", "IdhoaDonNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("IdhoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietHo__IDHoa__09A971A2");

                    b.HasOne("RestaurantManagement.Models.Entities.MonAn", "IdmonAnNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("IdmonAn")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietHo__IDMon__0A9D95DB");

                    b.Navigation("IdhoaDonNavigation");

                    b.Navigation("IdmonAnNavigation");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("RestaurantManagement.Models.Entities.NguyenLieu", "IdnguyenLieuNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("IdnguyenLieu")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__IDNgu__7C4F7684");

                    b.HasOne("RestaurantManagement.Models.Entities.PhieuNhapKho", "IdphieuNhapKhoNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("IdphieuNhapKho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__IDPhi__7B5B524B");

                    b.Navigation("IdnguyenLieuNavigation");

                    b.Navigation("IdphieuNhapKhoNavigation");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.DatBan", b =>
                {
                    b.HasOne("RestaurantManagement.Models.Entities.BanAn", "IdbanAnNavigation")
                        .WithMany("DatBans")
                        .HasForeignKey("IdbanAn")
                        .HasConstraintName("FK__DatBan__IDBanAn__5165187F");

                    b.HasOne("RestaurantManagement.Models.Entities.KhachHang", "IdkhachHangNavigation")
                        .WithMany("DatBans")
                        .HasForeignKey("IdkhachHang")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__DatBan__IDKhachH__5070F446");

                    b.Navigation("IdbanAnNavigation");

                    b.Navigation("IdkhachHangNavigation");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.HoaDon", b =>
                {
                    b.HasOne("RestaurantManagement.Models.Entities.BanAn", "BanAn")
                        .WithMany()
                        .HasForeignKey("BanAnIdbanAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantManagement.Models.Entities.DatBan", "DatBan")
                        .WithMany()
                        .HasForeignKey("DatBanIddatBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantManagement.Models.Entities.BanAn", "IdbanAnNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdbanAn")
                        .HasConstraintName("FK__HoaDon__IDBanAn__05D8E0BE");

                    b.HasOne("RestaurantManagement.Models.Entities.DatBan", "IddatBanNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IddatBan")
                        .HasConstraintName("FK__HoaDon__IDDatBan__06CD04F7");

                    b.HasOne("RestaurantManagement.Models.Entities.KhachHang", "IdkhachHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdkhachHang")
                        .HasConstraintName("FK__HoaDon__IDKhachH__03F0984C");

                    b.HasOne("RestaurantManagement.Models.Entities.NhanVien", "IdnhanVienNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdnhanVien")
                        .HasConstraintName("FK__HoaDon__IDNhanVi__04E4BC85");

                    b.HasOne("RestaurantManagement.Models.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangIdkhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BanAn");

                    b.Navigation("DatBan");

                    b.Navigation("IdbanAnNavigation");

                    b.Navigation("IddatBanNavigation");

                    b.Navigation("IdkhachHangNavigation");

                    b.Navigation("IdnhanVienNavigation");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.MonAnNguyenLieu", b =>
                {
                    b.HasOne("RestaurantManagement.Models.Entities.MonAn", "IdmonAnNavigation")
                        .WithMany("MonAnNguyenLieus")
                        .HasForeignKey("IdmonAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__MonAn_Ngu__IDMon__123EB7A3");

                    b.HasOne("RestaurantManagement.Models.Entities.NguyenLieu", "IdnguyenLieuNavigation")
                        .WithMany("MonAnNguyenLieus")
                        .HasForeignKey("IdnguyenLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__MonAn_Ngu__IDNgu__1332DBDC");

                    b.Navigation("IdmonAnNavigation");

                    b.Navigation("IdnguyenLieuNavigation");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.PhieuNhapKho", b =>
                {
                    b.HasOne("RestaurantManagement.Models.Entities.NhaCungCap", "IdnhaCungCapNavigation")
                        .WithMany("PhieuNhapKhos")
                        .HasForeignKey("IdnhaCungCap")
                        .HasConstraintName("FK__PhieuNhap__IDNha__787EE5A0");

                    b.HasOne("RestaurantManagement.Models.Entities.NhanVien", "IdnhanVienNavigation")
                        .WithMany("PhieuNhapKhos")
                        .HasForeignKey("IdnhanVien")
                        .HasConstraintName("FK__PhieuNhap__IDNha__778AC167");

                    b.Navigation("IdnhaCungCapNavigation");

                    b.Navigation("IdnhanVienNavigation");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.TaiKhoan", b =>
                {
                    b.HasOne("RestaurantManagement.Models.Entities.NhanVien", "IdnhanVienNavigation")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("RestaurantManagement.Models.Entities.TaiKhoan", "IDNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TaiKhoan__IDNhan__5EBF139D");

                    b.Navigation("IdnhanVienNavigation");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.ThanhToan", b =>
                {
                    b.HasOne("RestaurantManagement.Models.Entities.HoaDon", "IdhoaDonNavigation")
                        .WithMany("ThanhToans")
                        .HasForeignKey("IdhoaDon")
                        .IsRequired()
                        .HasConstraintName("FK__ThanhToan__IDHoa__0E6E26BF");

                    b.HasOne("RestaurantManagement.Models.Entities.KhachHang", "IdkhachHangNavigation")
                        .WithMany("ThanhToans")
                        .HasForeignKey("IdkhachHang")
                        .HasConstraintName("FK__ThanhToan__IDKha__0F624AF8");

                    b.Navigation("IdhoaDonNavigation");

                    b.Navigation("IdkhachHangNavigation");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.TonKho", b =>
                {
                    b.HasOne("RestaurantManagement.Models.Entities.Kho", "IdkhoNavigation")
                        .WithMany("TonKhos")
                        .HasForeignKey("Idkho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TonKho__IDKho__71D1E811");

                    b.HasOne("RestaurantManagement.Models.Entities.NguyenLieu", "IdnguyenLieuNavigation")
                        .WithMany("TonKhos")
                        .HasForeignKey("IdnguyenLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TonKho__IDNguyen__72C60C4A");

                    b.Navigation("IdkhoNavigation");

                    b.Navigation("IdnguyenLieuNavigation");
                });

            modelBuilder.Entity("TaiKhoanQuyen", b =>
                {
                    b.HasOne("RestaurantManagement.Models.Entities.Quyen", null)
                        .WithMany()
                        .HasForeignKey("Idquyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TaiKhoan___IDQuy__628FA481");

                    b.HasOne("RestaurantManagement.Models.Entities.TaiKhoan", null)
                        .WithMany()
                        .HasForeignKey("IdtaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TaiKhoan___IDTai__619B8048");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.BanAn", b =>
                {
                    b.Navigation("DatBans");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.DatBan", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.KhachHang", b =>
                {
                    b.Navigation("DatBans");

                    b.Navigation("HoaDons");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.Kho", b =>
                {
                    b.Navigation("TonKhos");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.MonAn", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("MonAnNguyenLieus");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.NguyenLieu", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("MonAnNguyenLieus");

                    b.Navigation("TonKhos");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.NhaCungCap", b =>
                {
                    b.Navigation("PhieuNhapKhos");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("PhieuNhapKhos");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("RestaurantManagement.Models.Entities.PhieuNhapKho", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });
#pragma warning restore 612, 618
        }
    }
}
